ignore:
  - 'Mini Model <minimodel@metamodel.me>'

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'Ingolf Steinhardt <git@e-spin.de>'

copy-left:
  'Christian Schiffler <c.schiffler@cyberspectrum.de>':
    - src/EventListener/DcGeneral/Table/Attribute/AbstractAbstainingListener.php
    - src/EventListener/DcGeneral/Table/Attribute/AttributeOptionsListener.php
    - src/EventListener/DcGeneral/Table/Attribute/LoadDistancesListener.php
    - src/EventListener/DcGeneral/Table/Attribute/OperationButtonListener.php
    - src/EventListener/DcGeneral/Table/Attribute/SaveDistancesListener.php
