services:
    metamodels.attribute_levenshtein.attribute_factory:
        class: MetaModels\AttributeLevenshteinBundle\Attribute\LevenshteinAttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
          - { name: metamodels.attribute_factory }

    metamodels.attribute_levenshtein.filter_factory:
        class: MetaModels\AttributeLevenshteinBundle\FilterSetting\LevenshteinFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }

    # Backward compatibility.
    metamodels.attribute_levenshtein.filter_setting_renderer_listener:
      deprecated: 'This service %alias_id% is deprecated since 2.2.0 and where removed in 3.0.'
      alias: '@MetaModels\AttributeLevenshteinBundle\EventListener\DcGeneral\Table\FilterSetting\TypeRendererListener'

    MetaModels\AttributeLevenshteinBundle\EventListener\DcGeneral\Table\FilterSetting\TypeRendererListener:
        public: false
        arguments:
          - "@metamodels.filter_setting_factory"
          - "@event_dispatcher"
          - "@metamodels.assets.icon_builder"
          - "@cca.dc-general.scope-matcher"
        tags:
          - {
              name: kernel.event_listener,
              event: 'dc-general.view.contao2backend.model-to-label',
              method: modelToLabel
            }

    metamodels.attribute_levenshtein.controller.ajax_search:
        class: MetaModels\AttributeLevenshteinBundle\Controller\Frontend\AjaxSearch
        arguments:
            - '@metamodels.factory'
        tags: ['controller.service_arguments']
